'use client';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,BarChart3,Check,ChevronDown,ClipboardList,Download,ExternalLink,FileText,FlaskConical,Layers,Plus,Search,Settings2,Target,Upload,X} from 'lucide-react';
import {ENGINES,metrics,list,parseCSV,toCSV,safeURL} from './lib/core.mjs';
type Item=Record<string,any>;
type Workspace={projects:Item[];prompts:Item[];answers:Item[];content:Item[];experiments:Item[]};
const tabs=[['Overview',BarChart3],['Prompt library',Search],['Answer evidence',Layers],['Content portfolio',FileText],['Experiments',FlaskConical],['Reports',ClipboardList],['Project settings',Settings2]] as const;
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID();
const fmt=(v:number|null)=>v===null?'—':v+'%';
const dateLabel=(s:string)=>s?new Date(s.includes('T')?s:s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Not set';
const field=(name:string,label:string,type='text',options?:string[],required=false)=>({name,label,type,options,required});
function download(name:string,text:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function LinkOut({url,label}:{url:string;label?:string}){const href=safeURL(url);return href?<a href={href} target='_blank' rel='noreferrer'>{label||url}<ExternalLink size={12}/></a>:<span>{label||url}</span>;}
export default function Studio(){
 const [data,setData]=useState<Workspace|null>(null),[version,setVersion]=useState(0),[projectId,setProjectId]=useState(''),[tab,setTab]=useState('Overview'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[failure,setFailure]=useState(''),[modal,setModal]=useState<Item|null>(null),[query,setQuery]=useState(''),[collection,setCollection]=useState('All collection methods'),[engine,setEngine]=useState('All surfaces'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selectedAnswer,setSelectedAnswer]=useState<Item|null>(null);
 const upload=useRef<HTMLInputElement>(null);const importKind=useRef('prompts');
 useEffect(()=>{fetch('/api/workspace').then(async r=>{const v:any=await r.json();if(!r.ok)throw Error(v.error||'Could not load workspace');setData(v.data);setVersion(v.version);setProjectId(v.data.projects[0]?.id||'');}).catch(e=>setFailure(e.message));},[]);
 useEffect(()=>{if(!modal&&!selectedAnswer)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector('[role=dialog]') as HTMLElement;const backgrounds=[document.querySelector('main'),document.querySelector('aside')];backgrounds.forEach(el=>el?.setAttribute('inert',''));const nodes=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]')||[]);nodes()[0]?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){setModal(null);setSelectedAnswer(null);}if(e.key==='Tab'){const all=nodes();const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>{backgrounds.forEach(el=>el?.removeAttribute('inert'));document.removeEventListener('keydown',handler);previous?.focus();};},[!!modal,!!selectedAnswer,busy]);
 const project=data?.projects.find(p=>p.id===projectId);
 const prompts=data?.prompts.filter(p=>p.projectId===projectId)||[];
 const allAnswers=data?.answers.filter(a=>a.projectId===projectId)||[];
 const answers=allAnswers.filter(a=>(collection==='All collection methods'||(a.collection||'Consumer UI')===collection)&&(engine==='All surfaces'||a.engine===engine)&&(!from||a.date.slice(0,10)>=from)&&(!to||a.date.slice(0,10)<=to));
 const stats=metrics(answers,prompts);
 const content=data?.content.filter(p=>p.projectId===projectId)||[];
 const experiments=data?.experiments.filter(p=>p.projectId===projectId)||[];
 const active=prompts.filter(p=>p.active);
 const pending=active.filter(p=>!answers.some(a=>a.promptId===p.id&&a.status==='Captured'));
 const names=new Map(prompts.map(p=>[p.id,p.text]));
 const brandRows=useMemo(()=>{const rows=answers.filter(a=>a.status==='Captured'&&a.assessmentReviewed!==false&&prompts.find(p=>p.id===a.promptId)?.group==='Discovery');const brands=[project?.name,...(project?.competitors||[])].filter(Boolean);return brands.map(name=>{const count=rows.filter(a=>list(a.brands).some(b=>b.toLowerCase()===name.toLowerCase())||(name===project?.name&&a.recommended)).length;return {name,count,rate:rows.length?Math.round(count/rows.length*100):null};}).sort((a,b)=>b.count-a.count);},[answers,project,prompts]);
 const sourceRows=useMemo(()=>{const map=new Map<string,{url:string;count:number;owned:boolean}>();for(const a of answers.filter(a=>a.status==='Captured')){for(const owned of [true,false])for(const url of new Set(list(owned?a.ownedCitations:a.thirdPartyCitations).filter(safeURL).map(original=>{const parsed=new URL(original);[...parsed.searchParams.keys()].filter(k=>k.startsWith('utm_')).forEach(k=>parsed.searchParams.delete(k));return parsed.toString();}))){const previous=map.get(url);map.set(url,{url,count:(previous?.count||0)+1,owned:owned||previous?.owned||false});}}return [...map.values()].sort((a,b)=>b.count-a.count).slice(0,8);},[answers]);
 const trend=useMemo(()=>{const days=[...new Set(answers.filter(a=>a.status==='Captured').map(a=>a.date.slice(0,10)))].sort().slice(-10);return days.map(day=>({day,...metrics(answers.filter(a=>a.date.slice(0,10)===day),prompts)}));},[answers,prompts]);
 async function save(next:Workspace){setBusy(true);setFailure('');try{const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:next,version})});const response:any=await r.json();if(!r.ok)throw Error(response.error||'Could not save');setData(next);setVersion(response.version);setNotice('Saved on this computer');setTimeout(()=>setNotice(''),4000);return true;}catch(e:any){setFailure(e.message);return false;}finally{setBusy(false);}}
 function open(kind:string,item?:Item){let values:Item=item?{...item}:{};let fields:Item[]=[];
 if(kind==='project'){values=item?{...item,competitors:item.competitors.join(', ')}:{};fields=[field('name','Company name','text',undefined,true),field('domain','Domain'),field('competitors','Competitors, comma-separated'),field('description','Buyer focus','textarea')];}
 if(kind==='prompt'){values=item?{...item}:{group:'Discovery',purpose:'',text:''};fields=[field('text','Exact buyer prompt','textarea',undefined,true),field('group','Prompt group','select',['Discovery','Comparison','Accuracy']),field('purpose','What does this test?','textarea')];}
 if(kind==='answer'){values=item?{...item}:{assessmentReviewed:false,promptId:active[0]?.id||'',engine:engine==='All surfaces'?'ChatGPT':engine,status:'Captured',date:today(),collection:'Consumer UI',provider:'',searchBackend:'',model:'',search:'Enabled',region:'US · English',run:'1',text:'',brands:'',ownedCitations:'',thirdPartyCitations:'',mentioned:false,recommended:false,checkedClaims:0,errorClaims:0,errors:'',framing:'Neutral / mixed',notes:''};fields=[field('promptId','Tracked prompt','prompt',undefined,true),field('engine','Search surface','select',ENGINES),field('status','Result status','select',['Captured','Blocked','No overview','Error']),field('date','Capture date','date',undefined,true),field('collection','Collection method','select',['Consumer UI','API']),field('provider','API provider / routing'),field('searchBackend','Search backend'),field('model','Model / mode'),field('search','Web search','select',['Enabled','Disabled','Unknown']),field('region','Region and language'),field('run','Independent run number','number'),field('text','Full answer text','textarea'),field('brands','Recommended brands, comma-separated'),field('ownedCitations','Company-owned citation URLs, one per line','textarea'),field('thirdPartyCitations','Third-party citation URLs, one per line','textarea'),field('assessmentReviewed','I reviewed the recommendation labels against the full answer','checkbox'),field('mentioned','Company mentioned','checkbox'),field('recommended','Company recommended','checkbox'),field('checkedClaims','Claims manually checked','number'),field('errorClaims','Verified incorrect claims','number'),field('errors','Verified errors and primary evidence','textarea'),field('framing','Recommendation framing','select',['Positive','Neutral / mixed','Negative','Not assessed']),field('notes','Interpretation / next action','textarea')];}
 if(kind==='content'){values=item||{decision:'Investigate',status:'Queued',prompts:[],owner:'',url:'',reason:'',baseline:'',change:'',shippedAt:'',metrics:''};values={...values,prompts:(values.prompts||[]).join(', ')};fields=[field('title','Page or work item','text',undefined,true),field('url','Page URL'),field('decision','Portfolio decision','select',['Investigate','Keep','Refresh','Consolidate','Prune']),field('status','Delivery status','select',['Queued','In progress','In review','Shipped','On hold']),field('owner','Owner'),field('prompts','Related prompt IDs, comma-separated'),field('reason','Decision and reasoning','textarea',undefined,true),field('baseline','Before-state / evidence','textarea'),field('change','Changes shipped / redirect target / rollback notes','textarea'),field('shippedAt','Ship date','date'),field('metrics','Traffic, sign-ups and follow-up findings','textarea')];}
 if(kind==='experiment'){values=item||{status:'Planned',prompts:[],hypothesis:'',intervention:'',success:'',control:'',start:'',end:'',finding:''};values={...values,prompts:(values.prompts||[]).join(', ')};fields=[field('title','Experiment name','text',undefined,true),field('hypothesis','Hypothesis','textarea',undefined,true),field('prompts','Related prompt IDs, comma-separated'),field('status','Status','select',['Planned','Running','Evaluating','Complete','On hold']),field('intervention','Intervention / exact changes','textarea'),field('success','Success criteria','textarea'),field('control','Control and fixed conditions','textarea'),field('start','Start date','date'),field('end','Review date','date'),field('finding','Results, limitations and next decision','textarea')];}
 setModal({kind,values,fields,editing:!!item});setFailure('');}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!data||!modal)return;const f=new FormData(e.currentTarget);const values={...modal.values,...Object.fromEntries(f)};for(const spec of modal.fields)if(spec.type==='checkbox')values[spec.name]=f.has(spec.name);
 const kind=modal.kind,collection=({project:'projects',prompt:'prompts',answer:'answers',content:'content',experiment:'experiments'} as Item)[kind];let item:Item={...values,id:modal.editing?values.id:uid(),...(kind!=='project'?{projectId}:{} )};const next=structuredClone(data);
 if(kind==='project'){item.competitors=list(values.competitors);item.domain=String(values.domain||'').replace(/^https?:\/\//,'').replace(/\/$/,'');item.description=values.description||'';}
 if(kind==='prompt'){item.version=modal.editing?values.version+1:1;item.createdAt=new Date().toISOString();item.active=true;item.purpose=values.purpose||'';if(modal.editing){item.id=uid();next.prompts=next.prompts.map(p=>p.id===values.id?{...p,active:false}:p);}}
 if(kind==='answer'){for(const key of ['checkedClaims','errorClaims','run'])item[key]=Number(values[key]||0);item.promptVersion=prompts.find(p=>p.id===item.promptId)?.version;item.promptText=names.get(item.promptId);item.createdAt=values.createdAt||new Date().toISOString();if(list(item.brands).some((b:string)=>b.toLowerCase()===project?.name.toLowerCase()))item.recommended=true;if(item.recommended){item.mentioned=true;if(!list(item.brands).some((b:string)=>b.toLowerCase()===project?.name.toLowerCase()))item.brands=[...list(item.brands),project?.name].join(', ');}if(item.status!=='Captured'){item.recommended=false;item.mentioned=false;item.checkedClaims=0;item.errorClaims=0;item.brands='';item.ownedCitations='';item.thirdPartyCitations='';}if(item.status==='Captured'&&!item.text.trim()){setFailure('Paste the full answer before marking it captured.');return;}if(item.errorClaims>item.checkedClaims){setFailure('Incorrect claims cannot exceed the number checked.');return;}if(item.status==='No overview'&&item.engine!=='Google AI Overviews'){setFailure('No overview is only valid for Google AI Overviews.');return;}}
 if(['content','experiment'].includes(kind)){item.prompts=list(values.prompts);const bad=item.prompts.filter((id:string)=>!prompts.some(p=>p.id===id));if(bad.length){setFailure('Unknown prompt IDs: '+bad.join(', '));return;}}
 const key=collection as keyof Workspace;next[key]=(modal.editing&&kind!=='prompt'?next[key].map(x=>x.id===item.id?item:x):[...next[key],item]) as Item[];
 if(await save(next)){setModal(null);if(kind==='project')setProjectId(item.id);}}
 async function importFile(file:File){if(!data)return;setFailure('');try{const text=await file.text();if(importKind.current==='backup'){const imported=JSON.parse(text);const next=imported.data||imported;if(!window.confirm('Replace this workspace with the imported backup? Export the current workspace first if you need to keep it.'))return;if(await save(next))setProjectId(next.projects[0]?.id||'');return;}
 const rows=parseCSV(text);if(!rows.length)throw Error('CSV has no data rows');const next=structuredClone(data);let added=0;
 if(importKind.current==='prompts'){for(const row of rows){const text=row.prompt||row.text;if(!text?.trim())throw Error('Every prompt row needs prompt or text.');const group=row.group||'Discovery';if(!['Discovery','Comparison','Accuracy'].includes(group))throw Error('Group must be Discovery, Comparison or Accuracy.');if(next.prompts.some(p=>p.projectId===projectId&&p.text===text&&p.active))continue;const requested=row.prompt_id||uid();const id=next.prompts.some(p=>p.id===requested)?uid():requested;next.prompts.push({id,projectId,text,group,purpose:row.purpose||'',version:1,active:true,createdAt:new Date().toISOString()});added++;}}
 else{for(const row of rows){if((row.status||'').toLowerCase()==='pending')continue;const promptId=row.prompt_id||row.promptId;const p=prompts.find(p=>p.id===promptId);if(!p)throw Error('Unknown prompt ID '+promptId);const engine=row.surface||row.engine;if(!ENGINES.includes(engine))throw Error('Unrecognized surface: '+engine);const status=({'captured':'Captured','blocked':'Blocked','no_overview':'No overview','no overview':'No overview','error':'Error'} as Item)[String(row.status).toLowerCase()];if(!status)throw Error('Result status must be captured, blocked, no_overview or error.');const answerText=row.text||row.full_answer||'';if(status==='Captured'&&!answerText.trim())throw Error('Captured rows need a text or full_answer column. File paths alone are not answer evidence.');const date=row.date||row.timestamp_timezone;if(!date||Number.isNaN(Date.parse(date)))throw Error('Each result needs a valid date or timestamp_timezone.');const id=row.id||uid();if(next.answers.some(a=>a.id===id))continue;const bool=(s:string)=>['true','yes','1'].includes(String(s).toLowerCase());next.answers.push({id,projectId,promptId,promptVersion:p.version,promptText:p.text,engine,status,date,collection:row.collection||'Consumer UI',provider:row.provider||'',searchBackend:row.searchBackend||'',model:row.model||row.model_or_mode||'',searchPerformed:row.searchPerformed==='true'?true:row.searchPerformed==='false'?false:undefined,search:row.search||row.search_enabled||'Unknown',region:row.region||'',run:Number(row.run||row.run_number||1),text:answerText,brands:row.brands||row.recommended_brands||'',ownedCitations:row.ownedCitations||'',thirdPartyCitations:row.thirdPartyCitations||row.third_party_citations||'',assessmentReviewed:bool(row.assessmentReviewed),mentioned:bool(row.mentioned),recommended:bool(row.recommended),checkedClaims:Number(row.checkedClaims||0),errorClaims:Number(row.errorClaims||0),errors:row.errors||row.verified_errors||'',framing:row.framing||'Not assessed',notes:row.notes||row.next_action||''});added++;}}
 for(const a of next.answers){const company=next.projects.find(p=>p.id===a.projectId)?.name;if(a.status==='Captured'&&list(a.brands).some((b:string)=>b.toLowerCase()===company?.toLowerCase())){a.recommended=true;a.mentioned=true;}}
 if(!added){setNotice('No new rows to import. Pending runs are left unscored.');return;}if(await save(next))setNotice(`Imported ${added} ${importKind.current}.`);
 }catch(e:any){setFailure(e.message);}finally{if(upload.current)upload.current.value='';}}
 function pickImport(kind:string){importKind.current=kind;upload.current?.click();}
 function report(){return `# ${project?.name} · Search & content report\nPeriod: ${from||'All recorded dates'} → ${to||'latest'}\nSurface filter: ${engine}\nCollection filter: ${collection}\n\n## Visibility\nCaptured answers: ${stats.captured}\nUnbranded discovery answers: ${stats.discovery}\nDiscovery recommendation rate: ${fmt(stats.recommendation)}\nDiscovery mention rate: ${fmt(stats.mention)}\nOwned citation rate: ${fmt(stats.citation)}\nClaim accuracy: ${fmt(stats.accuracy)} (${stats.checked} checked claims)\nCollection: API and consumer UI records are labeled separately; filter cohort before comparing\n\n## Competitors (discovery only)\n${brandRows.map(b=>`- ${b.name}: ${b.count} recommendations (${fmt(b.rate)})`).join('\n')}\n\n## Content decisions and shipped work\n${content.map(c=>`- ${c.title}: ${c.decision} / ${c.status}\n  Reason: ${c.reason}\n  Change: ${c.change||'Not shipped'}\n  Findings: ${c.metrics||'Not measured'}`).join('\n')}\n\n## Experiments\n${experiments.map(x=>`- ${x.title} (${x.status})\n  Hypothesis: ${x.hypothesis}\n  Intervention: ${x.intervention}\n  Finding: ${x.finding||'Pending'}`).join('\n')}\n\n## Answer findings / next actions\n${answers.filter(a=>a.notes||a.errors).map(a=>`- ${a.engine} / ${a.promptId} / ${a.date}: ${a.errors||''} ${a.notes||''}`).join('\n')||'No findings recorded.'}\n\n## Interpretation\nVisibility is a proxy, not attributed revenue. Branded comparisons and accuracy tests are excluded from discovery rates. Blocked/error/no-overview observations are unscored; Overview coverage includes completed Google searches. Missing evidence is not zero visibility. Compare fixed prompt versions and conditions before inferring movement.\n`;
 }
 if(!data)return <div className='loading'><span className='wordmark'>SuperMarketers<span>.</span></span><h1>Opening Search Studio</h1><p>{failure||'Loading your local workspace…'}</p>{failure&&<button onClick={()=>location.reload()}>Try again</button>}</div>;
 return <div className='shell'>
 <aside><div className='wordmark'>SuperMarketers<span>.</span></div><div className='product-name'>SEARCH STUDIO <span>01</span></div><label className='project-label'>WORKSPACE</label><div className='project-picker'><select aria-label='Select project' value={projectId} onChange={e=>{setProjectId(e.target.value);setQuery('');}}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><ChevronDown size={16}/></div><nav>{tabs.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>{setTab(name);setQuery('');}}><Icon size={18}/>{name}{name==='Prompt library'&&<small>{active.length}</small>}</button>)}</nav><div className='sidebar-bottom'><span className='green-dot'/>Local workspace<p>Evidence first.<br/>Ship. Measure. Improve.</p><button onClick={()=>open('project')}><Plus size={15}/>New project</button></div></aside>
 <main><header><div className='breadcrumb'>Workspace <span>/</span> {project?.name} <span>/</span> {tab}</div><div className='save-state'>{busy?'Saving…':notice?<><Check size={14}/>{notice}</>:'Local SQLite workspace'}</div></header>
 <section className='page'><div className='page-head'><div><div className='eyebrow'>{tab==='Overview'?'YOUR BUYER QUESTIONS, IN FOCUS':project?.name+' / SEARCH OPERATIONS'}</div><h1>{tab==='Overview'?'From answers to action.':tab}</h1><p>{({Overview:'See how buyers find you. Decide what to improve next.','Prompt library':'A repeatable question set for every company and every search surface.','Answer evidence':'Keep the exact answers and sources behind every number.','Content portfolio':'Decide what to keep, refresh, consolidate or remove—and record why.',Experiments:'Turn observed gaps into small tests with a clear next decision.',Reports:'A practical biweekly update: what moved, what shipped, what happens next.','Project settings':'Keep buyer focus, competitors and measurement rules explicit.'} as Item)[tab]}</p></div><div className='head-actions'><button className='button ghost' onClick={()=>download(`${project?.name}-workspace.json`,JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),data},null,2),'application/json')}><Download size={15}/>Backup</button><button className='button primary' onClick={()=>open(tab==='Prompt library'?'prompt':tab==='Content portfolio'?'content':tab==='Experiments'?'experiment':'answer')}><Plus size={16}/>{tab==='Prompt library'?'Add prompt':tab==='Content portfolio'?'Add page':tab==='Experiments'?'New experiment':'Capture answer'}</button></div></div>
 {failure&&<div className='alert' role='alert'>{failure}<button onClick={()=>setFailure('')} aria-label='Dismiss error'><X size={15}/></button></div>}
 {['Overview','Answer evidence','Reports'].includes(tab)&&<div className='filters'><span className='filter-label'><Settings2 size={14}/>View</span><select aria-label='Filter surface' value={engine} onChange={e=>setEngine(e.target.value)}>{['All surfaces',...ENGINES].map(x=><option key={x}>{x}</option>)}</select><select aria-label='Filter collection method' value={collection} onChange={e=>setCollection(e.target.value)}>{['All collection methods','API','Consumer UI'].map(x=><option key={x}>{x}</option>)}</select><label>From <input type='date' value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To <input type='date' min={from} value={to} onChange={e=>setTo(e.target.value)}/></label>{(from||to||engine!=='All surfaces'||collection!=='All collection methods')&&<button onClick={()=>{setFrom('');setTo('');setEngine('All surfaces');setCollection('All collection methods');}}>Reset</button>}<span className='filter-count'>{answers.length} observations</span></div>}
 {tab==='Overview'&&<>
 <div className='kpi-grid'>{[['Discovery recommendations',fmt(stats.recommendation),`${stats.discovery} unbranded answers`,Target],['Owned citations',fmt(stats.citation),`${stats.captured} captured answers`,Layers],['Verified claim accuracy',fmt(stats.accuracy),`${stats.checked} selected claims checked`,Check],['Captured answers',String(stats.captured),`${active.length} active prompts · 4 surfaces`,Search]].map(([label,value,sub,Icon]:any)=><article className='kpi' key={label}><div>{label}<Icon size={16}/></div><strong>{value}</strong><small>{sub}</small></article>)}</div>
 {!stats.captured&&<div className='baseline-banner'><div className='baseline-icon'><Target size={24}/></div><div><h3>Your baseline starts with one answer.</h3><p>{active.length?`${project?.name}'s prompt bank is ready. Capture real answers to unlock visibility, citations and competitor comparisons.`:'Add your buyer questions, then capture real answers to build your baseline.'}</p></div><button className='button dark' onClick={()=>{setTab('Prompt library');}}>Open prompt bank<ArrowUpRight size={15}/></button></div>}
 <div className='two-columns'><article className='panel'><div className='panel-head'><div><h2>Search surface coverage</h2><p>Four surfaces. One consistent evidence trail.</p></div><span className='badge'>LIVE RECORDS</span></div><div className='engine-list'>{ENGINES.filter(x=>x!=='Google AI Overviews').map((e:string,i:number)=>{const es=metrics(answers.filter(a=>a.engine===e),prompts);return <div className='engine-row' key={e}><span className={'engine-icon engine-'+i}>{['C','G','Cl','P'][i]}</span><div><strong>{e}</strong><small>{answers.find(a=>a.engine===e)?.provider?`${answers.find(a=>a.engine===e)?.provider} API · ${answers.find(a=>a.engine===e)?.model}`:'Record provider, model and search mode'}</small></div><div className='engine-stats'><strong>{es.captured}</strong><small>answers</small></div><span className='pill'>{fmt(es.recommendation)} recommended</span></div>;})}</div><div className='panel-foot'>Discovery mention rate: <b>{fmt(stats.mention)}</b> · Recommendation rates use reviewed answers. API results and consumer UI runs are different cohorts.</div></article>
 <article className='panel'><div className='panel-head'><div><h2>Who makes the shortlist?</h2><p>Unbranded discovery prompts only.</p></div><Target size={19}/></div><div className='competitors'>{brandRows.map((b:any,i:number)=><div key={b.name}><div className='bar-label'><span><small>{String(i+1).padStart(2,'0')}</small>{b.name}{b.name===project?.name&&<b>YOU</b>}</span><strong>{fmt(b.rate)}</strong></div><div className='bar'><div style={{width:(b.rate||0)+'%',background:b.name===project?.name?'var(--lime)':'#9ea79b'}}/></div></div>)}</div><div className='panel-foot'>{stats.discovery?'Recommendation frequency, not a market-share estimate.':'Waiting for discovery answers. No fabricated competitor scores.'}</div></article></div>
 <div className='two-columns'><article className='panel'><div className='panel-head'><div><h2>Visibility over time</h2><p>Discovery recommendation rate by capture date.</p></div></div>{trend.length?<div className='trend'>{trend.map((t:any)=><div key={t.day}><strong>{fmt(t.recommendation)}</strong><div style={{height:Math.max(3,(t.recommendation||0)*1.2)}}/><small>{t.day.slice(5)}</small><span>{t.discovery} answers</span></div>)}</div>:<div className='empty small'><BarChart3 size={28}/><h3>A trend needs repeated observations.</h3><p>Run the same prompt versions in consistent conditions, then compare dates.</p></div>}<div className='panel-foot'>Changes in prompt mix or engine mode can change the rate. Keep cohorts consistent.</div></article><article className='panel'><div className='panel-head'><div><h2>Next moves</h2><p>Connect the research to work that ships.</p></div></div><div className='next-list'><button onClick={()=>setTab('Prompt library')}><span>01</span><div><strong>Capture the baseline</strong><small>{pending.length} active prompts without a captured answer in this view</small></div><ArrowUpRight size={17}/></button><button onClick={()=>setTab('Content portfolio')}><span>02</span><div><strong>Make content decisions</strong><small>{content.filter(c=>c.status!=='Shipped').length} queued or ongoing work items</small></div><ArrowUpRight size={17}/></button><button onClick={()=>setTab('Experiments')}><span>03</span><div><strong>Test a focused intervention</strong><small>{experiments.filter(x=>x.status==='Running').length} running · {experiments.filter(x=>x.status==='Planned').length} planned</small></div><ArrowUpRight size={17}/></button></div></article></div>
 </>}
 {tab==='Overview'&&<article className='panel source-panel'><div className='panel-head'><div><h2>Sources behind the answers</h2><p>Pages cited most often in this view. Use the evidence to choose what to improve.</p></div><span className='badge'>CITATION MAP</span></div>{sourceRows.length?<div className='table-wrap'><table><thead><tr><th>Cited page</th><th>Source type</th><th>Answers citing it</th></tr></thead><tbody>{sourceRows.map(s=><tr key={s.url}><td><LinkOut url={s.url}/></td><td><span className='pill'>{s.owned?'Company-owned':'Third-party'}</span></td><td>{s.count}</td></tr>)}</tbody></table></div>:<div className='panel-foot'>Capture citation URLs with each answer to build the source map.</div>}</article>}
 {tab==='Prompt library'&&<><div className='toolbar'><div className='search-box'><Search size={16}/><input placeholder='Search questions, groups or purposes' aria-label='Search prompts' value={query} onChange={e=>setQuery(e.target.value)}/></div><button className='button ghost' onClick={()=>pickImport('prompts')}><Upload size={14}/>Import CSV</button><button className='button ghost' onClick={()=>download('prompt-bank.csv',toCSV(prompts.map(p=>({prompt_id:p.id,prompt:p.text,group:p.group,purpose:p.purpose,version:p.version,active:p.active}))), 'text/csv')}><Download size={14}/>Export</button></div><div className='summary-strip'><span><b>{active.length}</b> active prompts</span><span><b>{active.filter(p=>p.group==='Discovery').length}</b> discovery</span><span><b>{active.filter(p=>p.group==='Comparison').length}</b> comparison</span><span><b>{active.filter(p=>p.group==='Accuracy').length}</b> accuracy</span></div><div className='prompt-list'>{prompts.filter(p=>`${p.text} ${p.group} ${p.purpose}`.toLowerCase().includes(query.toLowerCase())).map(p=><article key={p.id} className={!p.active?'archived':''}><div className='prompt-meta'><span className={'tag tag-'+p.group.toLowerCase()}>{p.group}</span><code>{p.id.length>12?p.id.slice(0,8):p.id}</code><small>v{p.version}{!p.active?' · archived':''}</small></div><h3>{p.text}</h3><p>{p.purpose}</p><div className='prompt-actions'><span>{allAnswers.filter(a=>a.promptId===p.id&&a.status==='Captured').length} captured answers</span><button onClick={()=>navigator.clipboard.writeText(p.text).then(()=>setNotice('Prompt copied')).catch(()=>setFailure('Clipboard unavailable. Select the prompt text to copy it.'))}>Copy prompt</button>{p.active&&<><button onClick={()=>open('prompt',p)}>New version</button><button onClick={()=>{open('answer');setModal(m=>m?{...m,values:{...m.values,promptId:p.id}}:m);}}>Capture answer<ArrowUpRight size={13}/></button></>}</div></article>)}</div>{!prompts.length&&<Empty title='Add your first buyer question' detail='Create a prompt or import a CSV with prompt, group and purpose columns.'/>}<div className='method-note'>Discovery measures whether buyers find you. Comparison and accuracy prompts diagnose positioning and facts. New versions preserve historical answers.</div></>}
 {tab==='Answer evidence'&&<><div className='toolbar'><div className='search-box'><Search size={16}/><input placeholder='Search answer text, sources or notes' aria-label='Search answers' value={query} onChange={e=>setQuery(e.target.value)}/></div><button className='button ghost' onClick={()=>pickImport('answers')}><Upload size={14}/>Import CSV</button><button className='button ghost' onClick={()=>download('answer-evidence.csv',toCSV(answers), 'text/csv')}><Download size={14}/>Export</button><button className='button ghost' onClick={()=>download('answer-template.csv',toCSV([{prompt_id:active[0]?.id||'',surface:'ChatGPT',status:'captured',date:today(),model:'',text:'',recommended_brands:'',mentioned:'false',recommended:'false',ownedCitations:'',thirdPartyCitations:'',checkedClaims:0,errorClaims:0,notes:''}]),'text/csv')}>CSV template</button></div>{!answers.length?<Empty title='The evidence belongs here.' detail='Capture a full answer, its sources and the conditions of the run. Blocked runs and missing Overviews remain unscored.'/>:<div className='table-wrap'><table><thead><tr><th>Prompt / captured</th><th>Surface</th><th>Status</th><th>Recommended</th><th>Owned sources</th><th>Evidence</th></tr></thead><tbody>{answers.filter(a=>`${a.text} ${a.notes} ${a.ownedCitations} ${a.thirdPartyCitations} ${a.promptText}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)).map(a=><tr key={a.id}><td><strong className='truncate'>{a.promptText||names.get(a.promptId)}</strong><small>{dateLabel(a.date)} · v{a.promptVersion||1} · run {a.run}</small></td><td>{a.engine}<small>{a.collection||'Consumer UI'} · {a.model||'Mode not recorded'}</small></td><td><span className='pill'>{a.status}</span></td><td>{a.status==='Captured'?(a.assessmentReviewed===false?'Needs review':a.recommended?'Yes':'No'):'—'}</td><td>{a.status==='Captured'?list(a.ownedCitations).length:'—'}</td><td><button className='text-button' onClick={()=>setSelectedAnswer(a)}>Read answer<ArrowUpRight size={13}/></button></td></tr>)}</tbody></table></div>}<div className='method-note'>Answers are captured evidence. An API retrieval result is not interchangeable with a consumer chat answer.</div></>}
 {tab==='Content portfolio'&&<><div className='summary-strip'>{['Queued','In progress','In review','Shipped'].map(status=><span key={status}><b>{content.filter(c=>c.status===status).length}</b>{status}</span>)}</div><div className='work-grid'>{content.map(c=><article className='work-card' key={c.id}><div><span className='tag'>{c.decision}</span><span className='pill'>{c.status}</span></div><h2>{c.title}</h2><p>{c.reason}</p>{c.url&&<LinkOut url={c.url}/>}<dl><dt>Before-state</dt><dd>{c.baseline||'Evidence needed'}</dd><dt>Shipped change</dt><dd>{c.change||'Not shipped'}</dd><dt>Follow-up</dt><dd>{c.metrics||'Not yet measured'}</dd></dl><footer><span>{c.owner||'Owner unassigned'}{c.shippedAt?' · '+dateLabel(c.shippedAt):''}</span><button onClick={()=>open('content',c)}>Update<ArrowUpRight size={14}/></button></footer></article>)}</div>{!content.length&&<Empty title='Build an auditable content portfolio' detail='Give each page a decision, an owner and a record of the change. Check traffic and conversion data before pruning.'/>}<div className='method-note'>Pre-publish checks: source accuracy → brand voice → crawlability and canonicals → internal links and schema → human approval → rollback record.</div></>}
 {tab==='Experiments'&&<><div className='work-grid'>{experiments.map(x=><article className='work-card' key={x.id}><div><span className='tag'>EXPERIMENT</span><span className='pill'>{x.status}</span></div><h2>{x.title}</h2><p>{x.hypothesis}</p><dl><dt>Intervention</dt><dd>{x.intervention||'Define the change'}</dd><dt>Success criteria</dt><dd>{x.success||'Set before running'}</dd><dt>Control / fixed conditions</dt><dd>{x.control||'Define a comparison cohort'}</dd><dt>Finding</dt><dd>{x.finding||'Awaiting evidence'}</dd></dl><footer><span>{x.end?'Review '+dateLabel(x.end):'Review date not set'}</span><button onClick={()=>open('experiment',x)}>Update<ArrowUpRight size={14}/></button></footer></article>)}</div>{!experiments.length&&<Empty title='Start with a testable hypothesis' detail='Link an observed answer gap to a small change, define success and record the limitations.'/>}</>}
 {tab==='Reports'&&<><div className='report-layout'><article className='panel report-panel'><div className='panel-head'><div><h2>{project?.name} · Search & content</h2><p>{from||'All recorded dates'} → {to||'latest'} · {engine}</p></div><button className='button primary' onClick={()=>download(`${project?.name}-report-${today()}.md`,report())}><Download size={14}/>Export report</button></div><pre>{report()}</pre></article><div><article className='panel checklist'><h2>Biweekly reporting</h2><p>A useful report ends with a decision.</p>{['Compare the same prompt cohort','Explain recommendation and source shifts','Check factual errors against primary sources','Record pages and technical changes shipped','Review traffic and qualified sign-ups','Choose the next experiment'].map((x,i)=><div key={x}><span>{i+1}</span>{x}</div>)}</article><article className='panel checklist'><h2>Business outcomes</h2><p>Record GA4, Search Console and qualified sign-up findings on each content work item. These sources are not connected yet; visibility does not prove acquisition lift.</p></article></div></div></>}
 {tab==='Project settings'&&<div className='two-columns'><article className='panel settings-panel'><div className='panel-head'><div><h2>{project?.name}</h2><p>{project?.domain}</p></div><button className='button ghost' onClick={()=>open('project',project)}>Edit project</button></div><h3>Buyer focus</h3><p>{project?.description||'Add a buyer focus.'}</p><h3>Tracked competitors</h3><div className='chips'>{project?.competitors.map((c:string)=><span key={c} className='pill'>{c}</span>)}</div><h3>Data portability</h3><p>Your records are saved in your local SQLite workspace. Export a full JSON backup to move or restore them.</p><button className='button ghost' onClick={()=>pickImport('backup')}><Upload size={14}/>Restore JSON backup</button></article><article className='panel settings-panel'><h2>Measurement rules</h2><dl><dt>Discovery recommendations</dt><dd>Captured unbranded answers recommending the company ÷ reviewed captured unbranded answers.</dd><dt>Owned citations</dt><dd>Captured answers citing a company-owned URL ÷ all captured answers.</dd><dt>Verified claim accuracy</dt><dd>Correct manually checked claims ÷ checked claims. Blank until claims are checked.</dd><dt>Gemini and Google AI Overviews</dt><dd>Gemini is the Google model tracked here. Google AI Overviews is a different Google search surface and is not measured by Gemini API runs.</dd><dt>Review status</dt><dd>API imports are unreviewed. Open an answer, edit its labels and confirm review before recommendation rates include it. Citation metrics do not require recommendation review.</dd><dt>Collection</dt><dd>Manual capture, CSV import and a local resumable API runner. Provider keys stay outside the dashboard. Automated schedules are not enabled.</dd></dl></article></div>}
 <footer className='page-footer'><span>SuperMarketers. <b>Search Studio</b></span><span>Capture → Build → Approve → Ship → Improve</span></footer></section></main>
 <input ref={upload} type='file' accept='.csv,.json' hidden onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f);}}/>
 {modal&&<div className='modal-backdrop' onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setModal(null);}}><section className='modal' role='dialog' aria-modal='true' aria-labelledby='dialog-title'><div className='modal-head'><div><span className='eyebrow'>SEARCH STUDIO</span><h2 id='dialog-title'>{modal.editing?(modal.kind==='prompt'?'Create next prompt version':'Update '+modal.kind):'Add '+modal.kind}</h2></div><button aria-label='Close dialog' onClick={()=>setModal(null)}><X size={20}/></button></div><form onSubmit={submit}><div className='form-grid'>{modal.fields.map((spec:Item)=><label className={['textarea','prompt'].includes(spec.type)?'wide':''} key={spec.name}><span>{spec.label}{spec.required?' *':''}</span>{spec.type==='textarea'?<textarea name={spec.name} defaultValue={modal.values[spec.name]||''} rows={spec.name==='text'?5:3} required={spec.required}/>:spec.type==='select'?<select name={spec.name} defaultValue={modal.values[spec.name]||spec.options[0]}>{spec.options.map((x:string)=><option key={x}>{x}</option>)}</select>:spec.type==='prompt'?<select name={spec.name} defaultValue={modal.values[spec.name]} required>{prompts.filter(p=>p.active||p.id===modal.values.promptId).map(p=><option value={p.id} key={p.id}>{p.id.slice(0,8)} · {p.text}</option>)}</select>:spec.type==='checkbox'?<input type='checkbox' name={spec.name} defaultChecked={modal.values[spec.name]}/>:<input autoFocus={spec===modal.fields[0]} name={spec.name} type={spec.type} min={spec.type==='number'?0:undefined} defaultValue={modal.values[spec.name]??''} required={spec.required}/>}</label>)}</div>{failure&&<p className='form-error' role='alert'>{failure}</p>}<div className='modal-foot'><p>{modal.kind==='prompt'&&modal.editing?'Previous versions and answers stay intact.':'Saved locally. Export a backup to move devices.'}</p><button type='button' className='button ghost' onClick={()=>setModal(null)}>Cancel</button><button type='submit' className='button primary' disabled={busy||(!active.length&&modal.kind==='answer')}>{busy?'Saving…':'Save '+modal.kind}</button></div></form></section></div>}
 {selectedAnswer&&<div className='modal-backdrop'><section className='modal evidence-modal' role='dialog' aria-modal='true' aria-labelledby='answer-title'><div className='modal-head'><div><span className='eyebrow'>{selectedAnswer.engine} · {dateLabel(selectedAnswer.date)}</span><h2 id='answer-title'>Answer evidence</h2></div><button aria-label='Close answer' onClick={()=>setSelectedAnswer(null)}><X size={20}/></button></div><div className='evidence-body'><span className='pill'>{selectedAnswer.status}</span><h3>{selectedAnswer.promptText||names.get(selectedAnswer.promptId)}</h3><p className='evidence-context'>{selectedAnswer.collection||'Consumer UI'} · {selectedAnswer.provider||'Direct'} · v{selectedAnswer.promptVersion} · {selectedAnswer.model||'Mode not recorded'} · Search: {selectedAnswer.search}{selectedAnswer.searchPerformed===false?' (not invoked)':selectedAnswer.searchPerformed===true?' (invoked)':''} · {selectedAnswer.region} · Run {selectedAnswer.run} · {selectedAnswer.searchBackend||'Search backend not recorded'}</p><p>Recommendation review: {selectedAnswer.assessmentReviewed===false?'Pending human review':'Reviewed capture'}</p><pre>{selectedAnswer.text||'No generated answer captured.'}</pre><h3>Company-owned sources</h3>{list(selectedAnswer.ownedCitations).map((url:string)=><div key={url}><LinkOut url={url}/></div>)}<h3>Third-party sources</h3>{list(selectedAnswer.thirdPartyCitations).map((url:string)=><div key={url}><LinkOut url={url}/></div>)}<h3>Checked facts and findings</h3>{selectedAnswer.retrievedSources?.length>0&&<><h3>Retrieved sources (not counted as citations)</h3>{selectedAnswer.retrievedSources.map((source:Item,i:number)=><div key={i}><LinkOut url={source.url||source.uri} label={source.title||source.url||source.uri}/></div>)}</>}<p>{selectedAnswer.checkedClaims} claims checked · {selectedAnswer.errorClaims} verified errors</p><p>{selectedAnswer.errors||'No verified errors recorded.'}</p><p>{selectedAnswer.notes||'No next action recorded.'}</p></div><div className='modal-foot'><button className='button primary' onClick={()=>{open('answer',selectedAnswer);setSelectedAnswer(null);}}>Edit capture</button></div></section></div>}
 </div>;
}
function Empty({title,detail}:{title:string;detail:string}){return <div className='empty'><Layers size={32}/><h2>{title}</h2><p>{detail}</p></div>;}
